name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]

    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Modules 
      run: npm install
      run: npm install -g react-scripts
      run: npm install --prefix client

    - name: Run Linter
      run: npm run lint

    - name: Build Application 
      run: npm run client:build

    - name: Run Tests
      run: npm run test
